### ISSUE TITLE
为什么不可以fork再PR呢？，也让我可以知道我能改进的地方。

### ISSUE THREAD

**Issue by lilien1010** [anjia0532/lua-resty-maxminddb#1]
readme 写的很好，
但是大部分代码都是一致的，PR的话,让我也知道可以改进优化的地方，可以让更多的人看到。
另外 readme 里面有些地方地址是错的。

**Comment by anjia0532** [comment]
你好，readme和主代码，确实是以你的为基础版本。但是实际上是不管是readme还是[lib/resty/maxminddb.lua](https://github.com/anjia0532/lua-resty-maxminddb/blob/master/lib/resty/maxminddb.lua#L165) 部分都变更了很多。

因为 https://github.com/lilien1010/lua-resty-maxminddb 只可以获取area_code,不满足需求，所以决定自己改造。

比如 readme 仅 `Bug Reports`部分未变更，issues地址还是你的库的，哈哈（现已更正）
而 maxminddb.lua 中，仅`struct`全部和`_M:lookup(ip)`部分未变更，其余部分基本都变了。主要体现在，去除原有，仅能查询区域编码的函数，根据 [libmaxminddb/maxminddb.c#L1938](https://github.com/maxmind/libmaxminddb/blob/master/src/maxminddb.c#L1938) 库C编码，翻译成lua代码，实现了返回全部内容的函数`local function _dump_entry_data_list(entry_data_list,status,resultTab)` 这是我这版的精华所在。
用户可以根据 `local res,err = maxm:lookup(ngx.var.arg_ip or ngx.var.remote_addr)`  取到的`res`是一个json，可以`res['city']` `res['country']` ... 自主选择返回内容。更加灵活。

在由C移植到lua中遇到很多问题，在openresty 的邮件列表中也请教过别人，包括但不限于 [[求教]关于lua.ffi调用C](https://groups.google.com/forum/#!msg/openresty/Y3IBnpD68eQ/14M7rmz4AQAJ;context-place=forum/openresty)

下图为用beyond compare 比对的结果，红色部分是差异部分。对比发现，差异还是挺大的

![snipaste20180114_101026](https://user-images.githubusercontent.com/15098916/34912282-420c332e-f918-11e7-9db9-c4e8a019c72b.png)
