### ISSUE TITLE
Init two DBs under different names

### ISSUE THREAD

**Issue by jloh** [anjia0532/lua-resty-maxminddb#11]
Not sure if I'm trying to do something wrong here, but if I try and init two separate DBs under two name spaces, only the first DB gets used:

```
location = /test {
  default_type text/plain;
  content_by_lua_block {
    local cjson = require 'cjson'
    local geo   = require 'resty.maxminddb'
    local asn   = require 'resty.maxminddb'
    if not geo.initted() then
        geo.init("/usr/share/GeoIP/GeoLite2-City.mmdb")
    end
    if not asn.initted() then
        asn.init("/usr/share/GeoIP/GeoLite2-ASN.mmdb")
    end
    local res,err = geo.lookup("202.168.51.151")
    local asn_res,err = asn.lookup("202.168.51.151")

    if not res then
        ngx.log(ngx.ERR,'failed to lookup by ip ,reason:',err)
    end

    resp = {}

    ngx.say(cjson.encode(asn_res))
  }
}
```

In the above example even though I'm using the ASN DB (which works fine!) results are returned from the City DB. I'm assuming this is something to do with my understanding of how things are scoped? If you switch the order in which they're `initted` then results are returned from the ASN DB fine.

Thanks for the great module though!

**Comment by anjia0532** [comment]
the code:

https://github.com/anjia0532/lua-resty-maxminddb/blob/1d15251387d02ed3dccf7a5cff922368f9fec13c/lib/resty/maxminddb.lua#L157-L164

2ways

1. u can copy and rename the lua file. like `resty.maxminddb_city` and `resty.maxminddb_asn`

2. delete L158 and L168,(`if not initted then` and `end`) and inited lib in `init_by_lua` ,instead of `content_by_lua_block`

BTW,this lib only support city db(official 😊 ),not asn db.

**Comment by anjia0532** [comment]
ref https://github.com/anjia0532/lua-resty-maxminddb/issues/6#issuecomment-402084494 (sorry,this is chinese issues)

if u init db at `content_by_lua_block` ,easy to mem leak. so change to  
https://github.com/anjia0532/lua-resty-maxminddb/blob/1d15251387d02ed3dccf7a5cff922368f9fec13c/lib/resty/maxminddb.lua#L157-L164

**Comment by jloh** [comment]
Cool, thanks so much for confirming! Great module btw!

**Comment by anjia0532** [comment]
#35
