### ISSUE TITLE
Error at determine a boolean value 

### ISSUE THREAD

**Issue by JackyXiong** [anjia0532/lua-resty-maxminddb#19]
I create a mmdb file by using officail perl lib. 

The boolean type value read by officail python lib is correct. But use this lib is all false.

I think the problem is line 289.
```
 elseif data_type == MMDB_DATA_TYPE_BOOLEAN then
      val = entry_data_item.boolean == 1
```

 `entry_data_item.boolean ` is true or false in lua. No need to use equal number 1.

**Comment by anjia0532** [comment]
can u paste demo data? like ip addr?

**Comment by JackyXiong** [comment]
I print the value in log 
![image](https://user-images.githubusercontent.com/5654985/54732493-1094a000-4bcf-11e9-86ce-15c66f8c6176.png)
this is the log
![image](https://user-images.githubusercontent.com/5654985/54732432-b5fb4400-4bce-11e9-933d-5c5257f7ff86.png)

**Comment by anjia0532** [comment]
你版本是最新的么？我用127.0.0.104无法重现，你贴一下你的代码maxminddb.lua和nginx.conf

**Comment by JackyXiong** [comment]
lua 代码是 github 上最新的，我认为不是 ip 的问题。mmdb 文件是用官方的perl 库生成的自己的 ip 数据。字段定义如图
![image](https://user-images.githubusercontent.com/5654985/54803160-51f97e00-4ca9-11e9-98c2-ee7dd97ef15a.png)
在去 tags 里面的数据时出现的这种情况。

**Comment by anjia0532** [comment]
我这是用 https://github.com/maxmind/geoipupdate 下载的标准库，没用过perl，因为无法复现，所以不方便修改。你可以fork一份进行修改以自用。

**Comment by JackyXiong** [comment]
是的。已修改使用
