### ISSUE TITLE
not initialized

### ISSUE THREAD

**Issue by 0xfcryowbk2ca65z** [anjia0532/lua-resty-maxminddb#21]
not initialized

**Comment by anjia0532** [comment]
?

**Comment by 0xfcryowbk2ca65z** [comment]
4 failed to lookup by ip , reason :not initialized

**Comment by 0xfcryowbk2ca65z** [comment]
请问该怎么排查

**Comment by 0xfcryowbk2ca65z** [comment]
ngx.header.content_type="application/json;charset=utf8"

local json = require "cjson"
local zip = require 'zlib'
local uncompress = zip.inflate()
local compress = zip.deflate()
local geo = require 'resty.maxminddb'
local url = require "net.url"
local os = require "os"

if not geo.initted() then
     geo.init("/opt/openresty/luascript/GeoLite2-City.mmdb")
end

local ip_info,err = geo.lookup(remote_addr)
ngx.say(ngx.ERR,' failed to lookup by ip , reason :',err)

**Comment by anjia0532** [comment]
are u install maxmind/libmaxminddb first?

**Comment by 0xfcryowbk2ca65z** [comment]
install ,I switch ipip.net ipipfree.ipdb
