### ISSUE TITLE
Suggestion to make this usable by other context

### ISSUE THREAD

**Issue by shukitchan** [anjia0532/lua-resty-maxminddb#26]
Hi, First off, thanks so much by this project. I find it useful and the code is very solid. 

I would like to use this in other contexts, though (other than nginx). i.e. other platforms programmable through a luajit integration. I find that i need to make the following changes to make it work. 

https://gist.github.com/shukitchan/dc63b60e5d9c519b540390531d06ece3

Would you consider to reorganize your code a little bit so that it can be used easily in other luajit environments. Thanks.

**Comment by anjia0532** [comment]
follow your code
https://github.com/anjia0532/lua-resty-maxminddb/commit/d00c9f32224b4603f2e049b1edf2ddee9dd5b1bc

btw ,you can commit a new PR for this issues.

**Comment by shukitchan** [comment]
Looks good. Thanks.
