### ISSUE TITLE
maxminddb.lua 丢失城市数据

### ISSUE THREAD

**Issue by zhezi7** [anjia0532/lua-resty-maxminddb#30]
场景：使用lua-resty-maxminddb 开发两个接口：一个接口返回国家数据，一个接口返回城市数据。

在nginx reload之后，先访问国家数据接口，再访问城市数据接口，底层返回的数据，缺失city数据。正常访问ip是有城市数据的。

`{"continent":{"code":"SA","geoname_id":6255150,"names":{"ja":"南アメリカ","zh-CN":"南美洲","es":"Sudamérica","pt-BR":"América do Sul","de":"Südamerika","fr":"Amérique du Sud","ru":"Южная Америка","en":"South America"}},"country":{"names":{"ja":"ブラジル連邦共和国","zh-CN":"巴西","es":"Brasil","pt-BR":"Brasil","de":"Brasilien","fr":"Brésil","ru":"Бразилия","en":"Brazil"},"geoname_id":3469034,"iso_code":"BR"},"registered_country":{"names":{"ja":"ブラジル連邦共和国","zh-CN":"巴西","es":"Brasil","pt-BR":"Brasil","de":"Brasilien","fr":"Brésil","ru":"Бразилия","en":"Brazil"},"geoname_id":3469034,"iso_code":"BR"}}`

**Comment by anjia0532** [comment]
没太看懂，你有空可以提供下 Dockerfile 或者 DockerCompose 及最小复现步骤。

**Comment by zhezi7** [comment]
location_city.lua 从城市库获取城市信息:

```
local city_path = "./script/GeoLite2-City.mmdb"
local country_path = "./script/GeoLite2-Country.mmdb"

local request_method = ngx.var.request_method
local args
if "GET" == request_method then
    args = ngx.req.get_uri_args()
elseif "POST" == request_method then
    ngx.req.read_body()
    args = ngx.req.get_post_args()
end
local headers=ngx.req.get_headers()  

-- 有参数从参数中获取，不传参数，根据请求获取
local ip= args["ip"] or headers["X-REAL-IP"] or headers["X_FORWARDED_FOR"] or ngx.var.remote_addr or "0.0.0.0" 
local cjson = require "cjson.safe"
local geo = require 'resty.maxminddb'
if not geo.initted() then
    geo.init(city_path)
end

-- 查询本地库
local c,err = geo.lookup(ip)
if not c then
	ngx.log(ngx.ERR,'failed to lookup by ip: ', ip,',reason: ',err)
end

ngx.say(cjson.encode(c))
```

location_country.lua 从国家库获取国家信息

```
local city_path = "./script/GeoLite2-City.mmdb"
local country_path = "./script/GeoLite2-Country.mmdb"

local request_method = ngx.var.request_method
local args
if "GET" == request_method then
    args = ngx.req.get_uri_args()
elseif "POST" == request_method then
    ngx.req.read_body()
    args = ngx.req.get_post_args()
end
local ip = args["ip"]
local cjson = require "cjson.safe"
local geo = require 'resty.maxminddb'
if not geo.initted() then
    geo.init(country_path)
end

-- 查询本地库
local c,err = geo.lookup(ip)
if not c then
    ngx.log(ngx.ERR,'failed to lookup country by ip: ', ip,',reason: ',err)
end

ngx.say(cjson.encode(c))
```

nginx.conf 配置:

```
        location /location_city { 
            default_type 'application/json;charset=UTF-8';
            proxy_set_header        X-Real-IP       $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            content_by_lua_file script/location_city.lua;
        }

        location /location_country { 
            default_type 'application/json;charset=UTF-8';
            proxy_set_header        X-Real-IP       $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            content_by_lua_file script/location_country.lua;
        }
```

复现步骤：
1. 用同一个ip，先访问 /location_country接口，可以正常获取国家数据；
2. 再访问/location_city接口，期望从城市库获取到城市数据，但是结果有国家信息，没有城市数据；实际城市库中是有此ip数据。看起来像是底层处理时，直接用国家库处理的。

**Comment by anjia0532** [comment]
目前，本库唯一支持的是 `GeoLite2-City.mmdb`， 其余的 `GeoLite2-Country.mmdb`, `GeoLite2-ASN.mmdb`, `GeoIP2-ISP.mmdb` 我这边业务没有用到，所以没做深研究。可以去网上或者 issues 看看别人的方案，当然也欢迎提 PR。

但是，理论上城市库会返回国家的一些信息，不是很清楚，你既用城市库，又用国家库的意义在那。

看着像是 这个问题 https://github.com/anjia0532/lua-resty-maxminddb/issues/20 和 https://github.com/anjia0532/lua-resty-maxminddb/issues/11
