### ISSUE TITLE
bad argument #1 to 'concat' (table expected, got nil)

### ISSUE THREAD

**Issue by zhezi7** [anjia0532/lua-resty-maxminddb#4]
maxminddb.lua:323: bad argument #1 to 'concat' (table expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'concat'
	/Users/suriko/apps/openresty/lualib/resty/maxminddb.lua:323: in function 'lookup'

**Comment by anjia0532** [comment]
share your code plz.

**Comment by anjia0532** [comment]
https://github.com/anjia0532/lua-resty-maxminddb/blob/b01e4344234e91a3cf2b9bde3d44e5eef9567e4e/lib/resty/maxminddb.lua#L317-L323

**Comment by zhezi7** [comment]
![image](https://user-images.githubusercontent.com/6046361/40218902-c68860f2-5aa5-11e8-8cc5-abe9a993553d.png)

please  see the picture

**Comment by anjia0532** [comment]
like https://github.com/anjia0532/lua-resty-maxminddb#synopsis.

paste your invoke code

**Comment by anjia0532** [comment]
1. install all of the prerequisites   https://github.com/anjia0532/lua-resty-maxminddb#prerequisites
2. maxminddb's version
3. invoke code

**Comment by zhezi7** [comment]
I find what I changed, when it loaded, it shows an error about maxminddb, 
maxminddb.lua:151: dlopen(libmaxminddb.so, 5): image not found
So I changed from 
local maxm     = ffi.load('libmaxminddb.**so**') to 
local maxm     = ffi.load('libmaxminddb.**dylib**')
Maybe that's the reason.

I use Mac, do you know why it shows the error:
maxminddb.lua:151: dlopen(libmaxminddb.so, 5): image not found

**Comment by anjia0532** [comment]
u need https://github.com/maxmind/libmaxminddb#on-os-x-via-homebrew
